# Generated by Django 2.2.4 on 2019-08-14 21:28

import blog.models
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=255, verbose_name='نام')),
                ('LastName', models.CharField(max_length=255, verbose_name='نام خانوادگی')),
                ('Email', models.CharField(max_length=70, verbose_name='ایمیل')),
                ('mobile', models.CharField(max_length=11, verbose_name='موبایل')),
                ('avatar', models.ImageField(upload_to='', verbose_name='آواتار')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'نویسنده',
                'verbose_name_plural': 'نویسندگان',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=255, verbose_name='شناسه وب')),
                ('image', models.ImageField(upload_to='', verbose_name='عکس')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('slug', models.CharField(max_length=255, verbose_name='شناسه وب')),
                ('thumbNailImage', models.ImageField(upload_to='', verbose_name='عکس کوچک')),
                ('CoverImage', models.ImageField(upload_to='', verbose_name='عکس کاور')),
                ('headline', models.CharField(max_length=255, verbose_name='سر تیتر')),
                ('hasAudio', models.BooleanField(default=False, verbose_name='فایل صوتی دارد؟')),
                ('audioFile', models.FileField(upload_to='', verbose_name='فایل صوتی')),
                ('StoryType', enumfields.fields.EnumField(default=0, enum=blog.models.StoryType, max_length=10)),
                ('authorId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Author', verbose_name='نویسنده')),
                ('categoryId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='دسته بندی داستان')),
            ],
            options={
                'verbose_name': 'داستان',
                'verbose_name_plural': 'داستان ها',
            },
        ),
        migrations.CreateModel(
            name='TextStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PageNumber', models.IntegerField(default=0, verbose_name='شماره صفحه')),
                ('PageContent', models.TextField(verbose_name='محتوای صفحه')),
                ('storyId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Story', verbose_name='داستان')),
            ],
        ),
        migrations.CreateModel(
            name='DialogStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dialogTextType', enumfields.fields.EnumField(default=0, enum=blog.models.DialogTextType, max_length=10, verbose_name='نوع متن دیالوگ')),
                ('SayFrom', models.CharField(max_length=50, verbose_name='شخص گوینده')),
                ('SayTime', models.CharField(max_length=10, verbose_name='زمان دیالوگ')),
                ('SayText', models.TextField(verbose_name='متن دیالوگ')),
                ('storyId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Story', verbose_name='داستان')),
            ],
            options={
                'verbose_name': 'دیالوگ',
                'verbose_name_plural': 'دیالوگ ها',
            },
        ),
    ]
