# Generated by Django 2.2.4 on 2019-08-15 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textstory',
            options={'verbose_name': 'محتوای داستان', 'verbose_name_plural': 'محتوای داستان ها'},
        ),
    ]
