# Generated by Django 2.2.4 on 2019-08-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190815_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='audioFile',
            field=models.FileField(blank=True, upload_to='', verbose_name='فایل صوتی'),
        ),
        migrations.AlterField(
            model_name='story',
            name='hasAudio',
            field=models.BooleanField(default=True, verbose_name='فایل صوتی دارد؟'),
        ),
    ]
