# Generated by Django 2.2.4 on 2019-08-28 14:34

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190828_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='H:/Programming/Django/django-majara/uploads/AuthorAvatar/'), upload_to='', verbose_name='آواتار'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='H:/Programming/Django/django-majara/uploads/Category/'), upload_to='', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='story',
            name='CoverImage',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='H:/Programming/Django/django-majara/uploads/Story-CoverImage/'), upload_to='', verbose_name='عکس کاور'),
        ),
        migrations.AlterField(
            model_name='story',
            name='thumbNailImage',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='H:/Programming/Django/django-majara/uploads/Story-thumbNailImage/'), upload_to='', verbose_name='عکس کوچک'),
        ),
    ]
