# Generated by Django 2.2.4 on 2019-08-28 15:32

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190828_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(upload_to=blog.models.authorDirectory, verbose_name='آواتار'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to=blog.models.categoryDirectory, verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='story',
            name='CoverImage',
            field=models.ImageField(upload_to=blog.models.storyDirectory, verbose_name='عکس کاور'),
        ),
        migrations.AlterField(
            model_name='story',
            name='thumbNailImage',
            field=models.ImageField(upload_to=blog.models.storyDirectory, verbose_name='عکس کوچک'),
        ),
    ]
